//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package net.minecraft.tag;

import net.minecraft.block.Block;
import net.minecraft.tag.Tag.Identified;
import net.minecraft.util.registry.Registry;

public final class BlockTags {
    protected static final RequiredTagList<Block> REQUIRED_TAGS;
    public static final Identified<Block> WOOL;
    public static final Identified<Block> PLANKS;
    public static final Identified<Block> STONE_BRICKS;
    public static final Identified<Block> WOODEN_BUTTONS;
    public static final Identified<Block> BUTTONS;
    public static final Identified<Block> CARPETS;
    public static final Identified<Block> WOODEN_DOORS;
    public static final Identified<Block> WOODEN_STAIRS;
    public static final Identified<Block> WOODEN_SLABS;
    public static final Identified<Block> WOODEN_FENCES;
    public static final Identified<Block> PRESSURE_PLATES;
    public static final Identified<Block> WOODEN_PRESSURE_PLATES;
    public static final Identified<Block> STONE_PRESSURE_PLATES;
    public static final Identified<Block> WOODEN_TRAPDOORS;
    public static final Identified<Block> DOORS;
    public static final Identified<Block> SAPLINGS;
    public static final Identified<Block> LOGS_THAT_BURN;
    public static final Identified<Block> LOGS;
    public static final Identified<Block> DARK_OAK_LOGS;
    public static final Identified<Block> OAK_LOGS;
    public static final Identified<Block> BIRCH_LOGS;
    public static final Identified<Block> ACACIA_LOGS;
    public static final Identified<Block> JUNGLE_LOGS;
    public static final Identified<Block> SPRUCE_LOGS;
    public static final Identified<Block> CRIMSON_STEMS;
    public static final Identified<Block> WARPED_STEMS;
    public static final Identified<Block> BANNERS;
    public static final Identified<Block> SAND;
    public static final Identified<Block> STAIRS;
    public static final Identified<Block> SLABS;
    public static final Identified<Block> WALLS;
    public static final Identified<Block> ANVIL;
    public static final Identified<Block> RAILS;
    public static final Identified<Block> LEAVES;
    public static final Identified<Block> TRAPDOORS;
    public static final Identified<Block> SMALL_FLOWERS;
    public static final Identified<Block> BEDS;
    public static final Identified<Block> FENCES;
    public static final Identified<Block> TALL_FLOWERS;
    public static final Identified<Block> FLOWERS;
    public static final Identified<Block> PIGLIN_REPELLENTS;
    public static final Identified<Block> GOLD_ORES;
    public static final Identified<Block> IRON_ORES;
    public static final Identified<Block> DIAMOND_ORES;
    public static final Identified<Block> REDSTONE_ORES;
    public static final Identified<Block> LAPIS_ORES;
    public static final Identified<Block> COAL_ORES;
    public static final Identified<Block> EMERALD_ORES;
    public static final Identified<Block> COPPER_ORES;
    public static final Identified<Block> NON_FLAMMABLE_WOOD;
    public static final Identified<Block> CANDLES;
    public static final Identified<Block> DIRT;
    public static final Identified<Block> TERRACOTTA;
    public static final Identified<Block> FLOWER_POTS;
    public static final Identified<Block> ENDERMAN_HOLDABLE;
    public static final Identified<Block> ICE;
    public static final Identified<Block> VALID_SPAWN;
    public static final Identified<Block> IMPERMEABLE;
    public static final Identified<Block> UNDERWATER_BONEMEALS;
    public static final Identified<Block> CORAL_BLOCKS;
    public static final Identified<Block> WALL_CORALS;
    public static final Identified<Block> CORAL_PLANTS;
    public static final Identified<Block> CORALS;
    public static final Identified<Block> BAMBOO_PLANTABLE_ON;
    public static final Identified<Block> STANDING_SIGNS;
    public static final Identified<Block> WALL_SIGNS;
    public static final Identified<Block> SIGNS;
    public static final Identified<Block> DRAGON_IMMUNE;
    public static final Identified<Block> WITHER_IMMUNE;
    public static final Identified<Block> WITHER_SUMMON_BASE_BLOCKS;
    public static final Identified<Block> BEEHIVES;
    public static final Identified<Block> CROPS;
    public static final Identified<Block> BEE_GROWABLES;
    public static final Identified<Block> PORTALS;
    public static final Identified<Block> FIRE;
    public static final Identified<Block> NYLIUM;
    public static final Identified<Block> WART_BLOCKS;
    public static final Identified<Block> BEACON_BASE_BLOCKS;
    public static final Identified<Block> SOUL_SPEED_BLOCKS;
    public static final Identified<Block> WALL_POST_OVERRIDE;
    public static final Identified<Block> CLIMBABLE;
    public static final Identified<Block> SHULKER_BOXES;
    public static final Identified<Block> HOGLIN_REPELLENTS;
    public static final Identified<Block> SOUL_FIRE_BASE_BLOCKS;
    public static final Identified<Block> STRIDER_WARM_BLOCKS;
    public static final Identified<Block> CAMPFIRES;
    public static final Identified<Block> GUARDED_BY_PIGLINS;
    public static final Identified<Block> PREVENT_MOB_SPAWNING_INSIDE;
    public static final Identified<Block> FENCE_GATES;
    public static final Identified<Block> UNSTABLE_BOTTOM_CENTER;
    public static final Identified<Block> MUSHROOM_GROW_BLOCK;
    public static final Identified<Block> INFINIBURN_OVERWORLD;
    public static final Identified<Block> INFINIBURN_NETHER;
    public static final Identified<Block> INFINIBURN_END;
    public static final Identified<Block> BASE_STONE_OVERWORLD;
    public static final Identified<Block> STONE_ORE_REPLACEABLES;
    public static final Identified<Block> DEEPSLATE_ORE_REPLACEABLES;
    public static final Identified<Block> BASE_STONE_NETHER;
    public static final Identified<Block> CANDLE_CAKES;
    public static final Identified<Block> CAULDRONS;
    public static final Identified<Block> CRYSTAL_SOUND_BLOCKS;
    public static final Identified<Block> INSIDE_STEP_SOUND_BLOCKS;
    public static final Identified<Block> OCCLUDES_VIBRATION_SIGNALS;
    public static final Identified<Block> DRIPSTONE_REPLACEABLE_BLOCKS;
    public static final Identified<Block> CAVE_VINES;
    public static final Identified<Block> MOSS_REPLACEABLE;
    public static final Identified<Block> LUSH_GROUND_REPLACEABLE;
    public static final Identified<Block> AZALEA_ROOT_REPLACEABLE;
    public static final Identified<Block> SMALL_DRIPLEAF_PLACEABLE;
    public static final Identified<Block> BIG_DRIPLEAF_PLACEABLE;
    public static final Identified<Block> SNOW;
    public static final Identified<Block> AXE_MINEABLE;
    public static final Identified<Block> HOE_MINEABLE;
    public static final Identified<Block> PICKAXE_MINEABLE;
    public static final Identified<Block> SHOVEL_MINEABLE;
    public static final Identified<Block> NEEDS_DIAMOND_TOOL;
    public static final Identified<Block> NEEDS_IRON_TOOL;
    public static final Identified<Block> NEEDS_STONE_TOOL;
    public static final Identified<Block> FEATURES_CANNOT_REPLACE;
    public static final Identified<Block> LAVA_POOL_STONE_CANNOT_REPLACE;
    public static final Identified<Block> GEODE_INVALID_BLOCKS;
    public static final Identified<Block> ANIMALS_SPAWNABLE_ON;
    public static final Identified<Block> AXOLOTLS_SPAWNABLE_ON;
    public static final Identified<Block> GOATS_SPAWNABLE_ON;
    public static final Identified<Block> MOOSHROOMS_SPAWNABLE_ON;
    public static final Identified<Block> PARROTS_SPAWNABLE_ON;
    public static final Identified<Block> POLAR_BEARS_SPAWNABLE_ON_IN_FROZEN_OCEAN;
    public static final Identified<Block> RABBITS_SPAWNABLE_ON;
    public static final Identified<Block> FOXES_SPAWNABLE_ON;
    public static final Identified<Block> WOLVES_SPAWNABLE_ON;
    public static final Identified<Block> AZALEA_GROWS_ON;
    public static final Identified<Block> REPLACEABLE_PLANTS;
    public static final Identified<Block> CANTBEWITHERED;
    public static final Identified<Block> FLUIDS;
    public static final Identified<Block> CORRUPTED_MATERIALS;

    private BlockTags() {
    }

    private static Identified<Block> register(String id) {
        return REQUIRED_TAGS.add(id);
    }

    public static TagGroup<Block> getTagGroup() {
        return REQUIRED_TAGS.getGroup();
    }

    static {
        REQUIRED_TAGS = RequiredTagListRegistry.register(Registry.BLOCK_KEY, "tags/blocks");
        CANTBEWITHERED = register("cant_be_corrupted");
        CORRUPTED_MATERIALS = register("corrupted_materials");
        FLUIDS = register("fluids");
        WOOL = register("wool");
        PLANKS = register("planks");
        STONE_BRICKS = register("stone_bricks");
        WOODEN_BUTTONS = register("wooden_buttons");
        BUTTONS = register("buttons");
        CARPETS = register("carpets");
        WOODEN_DOORS = register("wooden_doors");
        WOODEN_STAIRS = register("wooden_stairs");
        WOODEN_SLABS = register("wooden_slabs");
        WOODEN_FENCES = register("wooden_fences");
        PRESSURE_PLATES = register("pressure_plates");
        WOODEN_PRESSURE_PLATES = register("wooden_pressure_plates");
        STONE_PRESSURE_PLATES = register("stone_pressure_plates");
        WOODEN_TRAPDOORS = register("wooden_trapdoors");
        DOORS = register("doors");
        SAPLINGS = register("saplings");
        LOGS_THAT_BURN = register("logs_that_burn");
        LOGS = register("logs");
        DARK_OAK_LOGS = register("dark_oak_logs");
        OAK_LOGS = register("oak_logs");
        BIRCH_LOGS = register("birch_logs");
        ACACIA_LOGS = register("acacia_logs");
        JUNGLE_LOGS = register("jungle_logs");
        SPRUCE_LOGS = register("spruce_logs");
        CRIMSON_STEMS = register("crimson_stems");
        WARPED_STEMS = register("warped_stems");
        BANNERS = register("banners");
        SAND = register("sand");
        STAIRS = register("stairs");
        SLABS = register("slabs");
        WALLS = register("walls");
        ANVIL = register("anvil");
        RAILS = register("rails");
        LEAVES = register("leaves");
        TRAPDOORS = register("trapdoors");
        SMALL_FLOWERS = register("small_flowers");
        BEDS = register("beds");
        FENCES = register("fences");
        TALL_FLOWERS = register("tall_flowers");
        FLOWERS = register("flowers");
        PIGLIN_REPELLENTS = register("piglin_repellents");
        GOLD_ORES = register("gold_ores");
        IRON_ORES = register("iron_ores");
        DIAMOND_ORES = register("diamond_ores");
        REDSTONE_ORES = register("redstone_ores");
        LAPIS_ORES = register("lapis_ores");
        COAL_ORES = register("coal_ores");
        EMERALD_ORES = register("emerald_ores");
        COPPER_ORES = register("copper_ores");
        NON_FLAMMABLE_WOOD = register("non_flammable_wood");
        CANDLES = register("candles");
        DIRT = register("dirt");
        TERRACOTTA = register("terracotta");
        FLOWER_POTS = register("flower_pots");
        ENDERMAN_HOLDABLE = register("enderman_holdable");
        ICE = register("ice");
        VALID_SPAWN = register("valid_spawn");
        IMPERMEABLE = register("impermeable");
        UNDERWATER_BONEMEALS = register("underwater_bonemeals");
        CORAL_BLOCKS = register("coral_blocks");
        WALL_CORALS = register("wall_corals");
        CORAL_PLANTS = register("coral_plants");
        CORALS = register("corals");
        BAMBOO_PLANTABLE_ON = register("bamboo_plantable_on");
        STANDING_SIGNS = register("standing_signs");
        WALL_SIGNS = register("wall_signs");
        SIGNS = register("signs");
        DRAGON_IMMUNE = register("dragon_immune");
        WITHER_IMMUNE = register("wither_immune");
        WITHER_SUMMON_BASE_BLOCKS = register("wither_summon_base_blocks");
        BEEHIVES = register("beehives");
        CROPS = register("crops");
        BEE_GROWABLES = register("bee_growables");
        PORTALS = register("portals");
        FIRE = register("fire");
        NYLIUM = register("nylium");
        WART_BLOCKS = register("wart_blocks");
        BEACON_BASE_BLOCKS = register("beacon_base_blocks");
        SOUL_SPEED_BLOCKS = register("soul_speed_blocks");
        WALL_POST_OVERRIDE = register("wall_post_override");
        CLIMBABLE = register("climbable");
        SHULKER_BOXES = register("shulker_boxes");
        HOGLIN_REPELLENTS = register("hoglin_repellents");
        SOUL_FIRE_BASE_BLOCKS = register("soul_fire_base_blocks");
        STRIDER_WARM_BLOCKS = register("strider_warm_blocks");
        CAMPFIRES = register("campfires");
        GUARDED_BY_PIGLINS = register("guarded_by_piglins");
        PREVENT_MOB_SPAWNING_INSIDE = register("prevent_mob_spawning_inside");
        FENCE_GATES = register("fence_gates");
        UNSTABLE_BOTTOM_CENTER = register("unstable_bottom_center");
        MUSHROOM_GROW_BLOCK = register("mushroom_grow_block");
        INFINIBURN_OVERWORLD = register("infiniburn_overworld");
        INFINIBURN_NETHER = register("infiniburn_nether");
        INFINIBURN_END = register("infiniburn_end");
        BASE_STONE_OVERWORLD = register("base_stone_overworld");
        STONE_ORE_REPLACEABLES = register("stone_ore_replaceables");
        DEEPSLATE_ORE_REPLACEABLES = register("deepslate_ore_replaceables");
        BASE_STONE_NETHER = register("base_stone_nether");
        CANDLE_CAKES = register("candle_cakes");
        CAULDRONS = register("cauldrons");
        CRYSTAL_SOUND_BLOCKS = register("crystal_sound_blocks");
        INSIDE_STEP_SOUND_BLOCKS = register("inside_step_sound_blocks");
        OCCLUDES_VIBRATION_SIGNALS = register("occludes_vibration_signals");
        DRIPSTONE_REPLACEABLE_BLOCKS = register("dripstone_replaceable_blocks");
        CAVE_VINES = register("cave_vines");
        MOSS_REPLACEABLE = register("moss_replaceable");
        LUSH_GROUND_REPLACEABLE = register("lush_ground_replaceable");
        AZALEA_ROOT_REPLACEABLE = register("azalea_root_replaceable");
        SMALL_DRIPLEAF_PLACEABLE = register("small_dripleaf_placeable");
        BIG_DRIPLEAF_PLACEABLE = register("big_dripleaf_placeable");
        SNOW = register("snow");
        AXE_MINEABLE = register("mineable/axe");
        HOE_MINEABLE = register("mineable/hoe");
        PICKAXE_MINEABLE = register("mineable/pickaxe");
        SHOVEL_MINEABLE = register("mineable/shovel");
        NEEDS_DIAMOND_TOOL = register("needs_diamond_tool");
        NEEDS_IRON_TOOL = register("needs_iron_tool");
        NEEDS_STONE_TOOL = register("needs_stone_tool");
        FEATURES_CANNOT_REPLACE = register("features_cannot_replace");
        LAVA_POOL_STONE_CANNOT_REPLACE = register("lava_pool_stone_cannot_replace");
        GEODE_INVALID_BLOCKS = register("geode_invalid_blocks");
        ANIMALS_SPAWNABLE_ON = register("animals_spawnable_on");
        AXOLOTLS_SPAWNABLE_ON = register("axolotls_spawnable_on");
        GOATS_SPAWNABLE_ON = register("goats_spawnable_on");
        MOOSHROOMS_SPAWNABLE_ON = register("mooshrooms_spawnable_on");
        PARROTS_SPAWNABLE_ON = register("parrots_spawnable_on");
        POLAR_BEARS_SPAWNABLE_ON_IN_FROZEN_OCEAN = register("polar_bears_spawnable_on_in_frozen_ocean");
        RABBITS_SPAWNABLE_ON = register("rabbits_spawnable_on");
        FOXES_SPAWNABLE_ON = register("foxes_spawnable_on");
        WOLVES_SPAWNABLE_ON = register("wolves_spawnable_on");
        AZALEA_GROWS_ON = register("azalea_grows_on");
        REPLACEABLE_PLANTS = register("replaceable_plants");
    }
}
